config/routes.rb
Rails.application.routes.draw do
  get 'account/profile'

  get 'account/settings'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resources :home, only: [:show]
  resources :setcardgame
  resources :setrules

  root to: "home#show"
end

app/models/movie.rb
class Movie < ActiveRecord::Base
    
    def self.all_ratings
        Movie.pluck(:rating).uniq
    end
end

app/models/user.rb
class User < ActiveRecord::Base
    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.name = auth.info.name
        user.oauth_token = auth.credentials.token
        user.oauth_expires_at = Time.at(auth.credentials.expires_at)
        user.save!
      end
    end
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  def profile
  end

  def settings
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

    def movie_params
        params.require(:movie).permit(:title, :rating, :description, :release_date)
    end

    def show
        id = params[:id] # retrieve movie ID from URI route
        @movie = Movie.find(id) # look up movie by unique ID
        # will render app/views/movies/show.<extension> by default
    end

    def index
        session[:sort] = params[:sort] ? params[:sort] : nil
        session[:ratings] = params[:ratings] ? params[:ratings] : nil

        if ((session[:sort] != params[:sort]) || (session[:ratings] != params[:ratings]))
            redirect_to(movie_path(:sort => session[:sort], :ratings => session[:ratings]))
        end

        @all_ratings = Movie.all_ratings
        @checked_ratings = session[:ratings].nil? ? @all_ratings : session[:ratings].keys
        @movies = Movie.where(:rating => @checked_ratings).order(session[:sort])
    end

    def new
        # default: render 'new' template
    end

    def create
        @movie = Movie.create!(movie_params)
        flash[:notice] = "#{@movie.title} was successfully created."
        redirect_to(movies_path)
    end

    def edit
        @movie = Movie.find(params[:id])
    end

    def update
        @movie = Movie.find(params[:id])
        @movie.update_attributes!(movie_params)
        flash[:notice] = "#{@movie.title} was successfully updated."
        redirect_to(movie_path(@movie))
    end

    def destroy
        @movie = Movie.find(params[:id])
        @movie.destroy
        flash[:notice] = "Movie '#{@movie.title}' deleted."
        redirect_to(movies_path)
    end
    
    # add class
    def add_class(header)
        params[:sort] == header ? 'hilite' : nil
    end
    helper_method(:add_class)

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/setcardgame_controller.rb
class SetcardgameController < ApplicationController
    def index
    end
end

app/controllers/setrules_controller.rb
class SetrulesController < ApplicationController
    def index
    end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  # Checks if a number is odd:
  def oddness(count)
    count.odd? ?  "odd" :  "even"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/setcardgame_helper.rb
module SetcardgameHelper
end

app/helpers/setrules_helper.rb
module SetrulesHelper
end

app/views/home/show.html.haml
.home
  .button= link_to "Play", "/setcardgame"
  .button= link_to "Rules", "/setrules"
  .button= link_to "Profile", "/account/profile"
  .button= link_to "Settings", "/account/settings"
  .button
    %span
      %strike Stats
      (Coming Soon)
  .button
    %span
      %strike Friends
      (Coming Soon)

app/views/layouts/application.html.haml
!!!
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no' }
    %title Set Card Game
    = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %main#main.main
      %p= link_to "Home", "/"
      - if flash[:notice]
        #notice.notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.warning.message= flash[:warning]
      = render :partial => 'shared/signon'

app/views/movies/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Update Movie Info'

app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
-# Title of the view
%h1 All Movies

-# Form to filter by ratings
= form_tag movies_path, :id => 'ratings_form', :method => :get do
  -# regular text
  Include:
  -# Loop through each rating
  - @all_ratings.each do |rating|
    -# Display name of the current rating
    = label_tag("ratings[#{rating}]", rating)
    -# Display checkbox for current rating
    = check_box_tag("ratings[#{rating}]", 1, @checked_ratings.include?(rating), :id => "ratings_#{rating}")
  -# Submit button
  = button_tag('Refresh', :type => 'submit', :id => 'ratings_submit')
  -#= submit_tag 'Refresh'

-# Table of movies
%table#movies.movies
  %thead
    -# Row to display table headers
    %tr
      %th{:class => add_class('title')}= link_to("Movie Title", movies_path(:sort => 'title'), :id => 'title_header')
      %th Rating
      %th{:class => add_class('release_date')}= link_to("Release Date", movies_path(:sort => 'release_date'), :id => 'release_date_header')
      %th More Info
  %tbody
    -# Loop through each movie
    - @movies.each do |movie|
      -# Display data for current movie according to table headers
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to("More about #{movie.title}", movie_path(movie))

-# Link to add a new movies
= link_to('Add new movie', new_movie_path)

app/views/movies/new.html.haml
%h1 Create New Movie

= form_tag movies_path do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes'

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description

= link_to 'Edit', edit_movie_path(@movie)
= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to movie list', movies_path

app/views/setcardgame/index.html.haml
#set-card-app
  #set-app.set-game
  %h2#set-matches

= javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/setrules/index.html.haml
#set-card-rules.set-rules
  %h1 Instructions
  %p
    The object of the game is to identify a
    %b SET
    of 3 cards from 12 cards placed face up on the game table. Each card has four features, which can vary as follows:

  %p
    %b SHAPE
  %ul
    %li Ovals,
    %li Squiggles,
    %li or Diamonds

  %p
    %b COLOR
  %ul
    %li Red,
    %li Purple,
    %li or Green

  %p
    %b NUMBER
  %ul
    %li One,
    %li Two,
    %li or Three
      
  %p
    %b SHADING
  %ul
    %li Solid,
    %li Striped,
    %li or Outlined
  
  %p
    A
    %b SET
    consists of 3 cards in which each of the cards' features, looked at one-by-one, are the
    %i same
    on each card, or are
    %i different
    on each card. All of the features must separately satisfy this rule. In other words:
    %i shape
    must be either the same on all 3 cards, or different on each of the 3 cards;
    %i color
    must be either the same on all 3 cards, or different on each of the 3, etc.
    SET INSTRUCTIONS
    
  %p
    Number of Players: 1 or more

    The object of the game is to identify a SET of 3 cards from 12 cards 

    placed face on the the app. Each card has four featurs, which can 
    
    vary: 

    %b Shape 
    %b Color
    %b Number
    %b Shading

  %p
    %b A QUICK CHECK - Is it a SET?

    if 2 cards are the same and 1 card is different in any feature, then 

    it is not a SET. For example, if 2 are red and 1 is purple then it is 

    not a SET. A SET must be either all the same OR all different in each 

    individual feature. 
  
  %p
    %b EASY START

    For a quick introduction, start with the small deck(just the solid 

    symbols). This eliminates one feature, shading. Once you can quickly 

    see a SET when playing the 3 feature version, shuffle the 2 decks 

    together to play the full game. 
  
  %p
    
    %b THE PLAY

    The dealer shuffles the cards and lays 12 face up on the table
    (in a rectangle) so that they can be seen by all. Players remove SETs 

    of 3 cards from anywhere on the table. Each SET is checked by the 

    other players. if correct, the SET is kept by the player for one 

    point and the dealer replaces the 3 cards with 3 from the deck. A 

    player must call SET before picking up the cards. There are no turns, 

    the first player to call SET gets control of the board. After he/she 

    has called SET, no other player can pick up cards until that player 

    has finished. The SET must be picked up within a few seconds after 

    calling it. if a player calls SET and does not have one, or if the 

    SET is incorrect, he or she loses one point, and the 3 cards are 

    returned to the table. 

app/views/shared/_signon.html.haml
- if current_user
  Signed in as
  %strong= current_user.name
  !
  = link_to "Sign out", signout_path, id: "sign_out"
  = yield
- else
  = link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in"